# Configuration for GitHub Copilot Actions
# This file configures setup steps that run before the firewall is enabled,
# preventing telemetry calls that would otherwise be blocked.
#
# Reference: https://gh.io/copilot/actions-setup-steps

# Environment variables to set for all Copilot agent sessions
env:
  ASTRO_TELEMETRY_DISABLED: "1"
