import fs from 'node:fs';
import path from 'node:path';
import type { Manifest } from '../../../src/types';

/**
 * Load the manifest generated by the kolay plugin at build time
 * During development or initial build, the manifest may not exist yet
 */
export async function loadManifest(): Promise<Manifest> {
  // Try multiple possible locations for the manifest
  const possiblePaths = [
    path.resolve(process.cwd(), 'public/docs/manifest.json'),
    path.resolve(process.cwd(), 'dist/docs/manifest.json'),
    path.resolve(process.cwd(), 'kolay-manifest/manifest.json'),
  ];
  
  for (const manifestPath of possiblePaths) {
    try {
      if (fs.existsSync(manifestPath)) {
        const content = fs.readFileSync(manifestPath, 'utf-8');
        try {
          return JSON.parse(content);
        } catch (parseError) {
          console.warn(`Failed to parse JSON from ${manifestPath}:`, parseError);
        }
      }
    } catch (readError) {
      console.warn(`Failed to read manifest from ${manifestPath}:`, readError);
    }
  }
  
  console.warn('Manifest not found in any expected location, returning fallback structure');
  // Return fallback structure with expected groups
  return {
    groups: [
      { name: 'root', list: [], tree: { path: '/', name: 'root', pages: [] } },
      { name: 'Runtime', list: [], tree: { path: '/Runtime', name: 'Runtime', pages: [] } },
    ],
  };
}

/**
 * Convert a slug to a readable title
 * @param slug - The URL slug (e.g., "api-docs" or "component-signature")
 * @returns A formatted title string (e.g., "Api Docs" or "Component Signature")
 */
export function slugToTitle(slug: string | undefined): string {
  if (!slug) return 'Docs';
  const lastPart = slug.split('/').pop() || '';
  return lastPart
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
