import fs from 'node:fs';
import path from 'node:path';
import type { Manifest } from '../../../src/types';

/**
 * Load the manifest generated by the kolay plugin at build time
 */
export async function loadManifest(): Promise<Manifest> {
  const manifestPath = path.resolve(process.cwd(), 'public/docs/manifest.json');
  
  try {
    const content = fs.readFileSync(manifestPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.warn('Failed to load manifest from', manifestPath, error);
    // Return empty manifest if file doesn't exist yet
    return { groups: [] };
  }
}

/**
 * Convert a slug to a readable title
 */
export function slugToTitle(slug: string | undefined): string {
  if (!slug) return 'Docs';
  const lastPart = slug.split('/').pop() || '';
  return lastPart
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
